// SPDX-License-Identifier: Apache-2.0
//! Tool receipts (`ROADMAP.md` §7.4; Phase 2). Defends against hallucinated tool
//! results (invariant 10): **no receipt ⇒ no model-visible claim that a tool
//! ran.** Receipts are generated by CrustCore, never the model, and are verified
//! during replay/inspect (`docs/receipts.md`).
//!
//! A receipt is both **authenticated** (a MAC keyed by a secret only CrustCore
//! holds — so the model/worker cannot forge one) and **chained** (each commits to
//! the previous receipt's hash — so deletion/reorder/insertion is detected). The
//! hash and MAC are the vendored SHA-256 / HMAC-SHA-256 in `crustcore-types`.
#![forbid(unsafe_code)]

use crustcore_types::{hmac_sha256, sha256, ArtifactId, EventSeq, JobId, TaskId, ToolCallId};

/// The genesis `prev_receipt_hash`: the first receipt chains from all-zeros.
pub const GENESIS_RECEIPT_HASH: [u8; 32] = [0u8; 32];

/// The MAC key CrustCore uses to authenticate receipts. The model/worker never
/// holds this, which is what makes receipts unforgeable (`docs/receipts.md` §6).
///
/// Its bytes are never printed (`Debug` is redacted), it is not `Serialize`, not
/// `Clone` (so the key is not casually duplicated around memory), and it is
/// best-effort zeroed on drop — consistent with the secret-handling discipline
/// (invariants 1–3).
pub struct MacKey([u8; 32]);

impl MacKey {
    /// Wraps 32 bytes of key material.
    #[must_use]
    pub fn new(bytes: [u8; 32]) -> Self {
        MacKey(bytes)
    }

    fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

impl core::fmt::Debug for MacKey {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("MacKey(***)")
    }
}

impl Drop for MacKey {
    fn drop(&mut self) {
        // Best-effort scrub so the key does not linger in freed memory. Without
        // `unsafe`/`zeroize` (forbidden/avoided here) the optimizer *may* elide
        // this; it is defense-in-depth, not a guarantee.
        self.0.fill(0);
    }
}

/// A receipt binding a model-visible tool result to a real tool call.
///
/// Contains only hashes and ids — **never** secret values (invariant 10).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ToolReceipt {
    /// Task the call ran under.
    pub task_id: TaskId,
    /// Job the call ran under.
    pub job_id: JobId,
    /// The specific tool call.
    pub tool_call_id: ToolCallId,
    /// Hash of the tool name.
    pub tool_name_hash: [u8; 32],
    /// Hash of the (canonicalized) arguments.
    pub args_hash: [u8; 32],
    /// Hash of the result.
    pub result_hash: [u8; 32],
    /// Hashes of any artifacts produced (bounded).
    pub artifact_hashes: Vec<ArtifactId>,
    /// The event sequence this receipt corresponds to. It is MAC-bound (so it
    /// cannot be altered), but this crate does not cross-check that the event log
    /// actually has a matching `ToolCall*` frame at `event_seq` — that join is
    /// added when the verify loop wires receipts to the log.
    /// TODO(P5): `verify_against_log` cross-checking `event_seq` → event frame.
    pub event_seq: EventSeq,
    /// Hash of the previous receipt (chains receipts).
    pub prev_receipt_hash: [u8; 32],
    /// MAC over the receipt (keyed by CrustCore, not the model).
    pub mac: [u8; 32],
}

impl ToolReceipt {
    /// Whether `result` hashes to this receipt's `result_hash` — i.e. the shown
    /// result is the one that was actually produced (`docs/receipts.md` §4). The
    /// model cannot show a different result without breaking this.
    #[must_use]
    pub fn result_matches(&self, result: &[u8]) -> bool {
        sha256(result) == self.result_hash
    }

    /// Whether `args` hashes to this receipt's `args_hash` — i.e. the result is
    /// tied to a call made with exactly these (canonicalized) arguments
    /// (`docs/receipts.md` §4). Two calls to the same tool with different args
    /// yield distinguishable receipts, so a result cannot be re-attributed to a
    /// different call's inputs.
    #[must_use]
    pub fn args_matches(&self, args: &[u8]) -> bool {
        sha256(args) == self.args_hash
    }

    /// Whether this receipt chains directly after `prev` (its `prev_receipt_hash`
    /// equals the hash of `prev`'s body).
    #[must_use]
    pub fn links_to(&self, prev: &ToolReceipt) -> bool {
        self.prev_receipt_hash == receipt_chain_hash(prev)
    }
}

/// The committed fields of a tool call, used to mint a receipt. `tool_name`,
/// `args`, and `result` are the raw (already-redacted, if needed) bytes; the
/// receipt stores only their hashes.
pub struct ReceiptParams<'a> {
    /// Task the call ran under.
    pub task_id: TaskId,
    /// Job the call ran under.
    pub job_id: JobId,
    /// The specific tool call.
    pub tool_call_id: ToolCallId,
    /// The tool name bytes.
    pub tool_name: &'a [u8],
    /// The (canonicalized) argument bytes.
    pub args: &'a [u8],
    /// The result bytes shown to the model.
    pub result: &'a [u8],
    /// Content hashes of any produced artifacts.
    pub artifacts: &'a [ArtifactId],
    /// The event-log seq this receipt anchors to.
    pub event_seq: EventSeq,
}

/// Why a receipt chain failed to verify.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReceiptBreak {
    /// `prev_receipt_hash` did not match the previous receipt's chain hash.
    ChainMismatch,
    /// The MAC did not verify (forged or tampered receipt).
    BadMac,
    /// The receipts verify but are not the complete minted chain — trailing
    /// receipts were dropped (`verify_complete` only).
    EndTruncated,
}

/// The result of verifying a receipt chain.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReceiptStatus {
    /// Every receipt verified.
    Intact {
        /// Number of receipts verified.
        count: u64,
    },
    /// A receipt failed; reports its index and reason.
    Broken {
        /// Index of the failing receipt.
        index: u64,
        /// What went wrong.
        reason: ReceiptBreak,
    },
}

impl ReceiptStatus {
    /// Whether the whole chain verified.
    #[must_use]
    pub fn is_intact(self) -> bool {
        matches!(self, ReceiptStatus::Intact { .. })
    }
}

/// The canonical body bytes of a receipt, **excluding** the MAC. Both the MAC and
/// the chain hash are computed over this, so the order here is the format.
fn receipt_body(r: &ToolReceipt) -> Vec<u8> {
    let mut b =
        Vec::with_capacity(16 + 16 + 16 + 32 * 3 + 4 + r.artifact_hashes.len() * 32 + 8 + 32);
    b.extend_from_slice(&r.task_id.0.to_le_bytes());
    b.extend_from_slice(&r.job_id.0.to_le_bytes());
    b.extend_from_slice(&r.tool_call_id.0.to_le_bytes());
    b.extend_from_slice(&r.tool_name_hash);
    b.extend_from_slice(&r.args_hash);
    b.extend_from_slice(&r.result_hash);
    b.extend_from_slice(&(r.artifact_hashes.len() as u32).to_le_bytes());
    for a in &r.artifact_hashes {
        b.extend_from_slice(&a.0);
    }
    b.extend_from_slice(&r.event_seq.0.to_le_bytes());
    b.extend_from_slice(&r.prev_receipt_hash);
    b
}

/// The chain hash of a receipt: `H(body)`. The next receipt's
/// `prev_receipt_hash` equals this.
fn receipt_chain_hash(r: &ToolReceipt) -> [u8; 32] {
    sha256(&receipt_body(r))
}

/// Constant-time comparison of two 32-byte tags (avoids MAC timing leaks).
fn ct_eq(a: &[u8; 32], b: &[u8; 32]) -> bool {
    let mut diff = 0u8;
    for i in 0..32 {
        diff |= a[i] ^ b[i];
    }
    diff == 0
}

/// Mints and verifies a chain of [`ToolReceipt`]s under a CrustCore-held key.
#[derive(Debug)]
pub struct ReceiptChain {
    key: MacKey,
    head: [u8; 32],
    count: u64,
}

impl ReceiptChain {
    /// A fresh chain keyed by `key`, starting at the genesis hash.
    #[must_use]
    pub fn new(key: MacKey) -> Self {
        ReceiptChain {
            key,
            head: GENESIS_RECEIPT_HASH,
            count: 0,
        }
    }

    /// Number of receipts minted.
    #[must_use]
    pub fn len(&self) -> u64 {
        self.count
    }

    /// Whether any receipts have been minted.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.count == 0
    }

    /// Mints a receipt: hashes the tool name/args/result, links it to the current
    /// chain head, and authenticates it with the MAC key. Advances the head.
    pub fn mint(&mut self, params: &ReceiptParams<'_>) -> ToolReceipt {
        let mut receipt = ToolReceipt {
            task_id: params.task_id,
            job_id: params.job_id,
            tool_call_id: params.tool_call_id,
            tool_name_hash: sha256(params.tool_name),
            args_hash: sha256(params.args),
            result_hash: sha256(params.result),
            artifact_hashes: params.artifacts.to_vec(),
            event_seq: params.event_seq,
            prev_receipt_hash: self.head,
            mac: [0u8; 32],
        };
        let body = receipt_body(&receipt);
        receipt.mac = hmac_sha256(self.key.as_bytes(), &body);
        self.head = sha256(&body);
        self.count += 1;
        receipt
    }

    /// The current chain head: `H(body)` of the last minted receipt (genesis if
    /// none). Persist this out-of-band to anchor [`ReceiptChain::verify_complete`]
    /// against trailing-receipt deletion.
    #[must_use]
    pub fn head(&self) -> [u8; 32] {
        self.head
    }

    /// Walks the receipts, checking each `prev_receipt_hash` link and MAC, and
    /// returns the status plus the final computed chain hash.
    fn walk(&self, receipts: &[ToolReceipt]) -> (ReceiptStatus, [u8; 32]) {
        let mut expected_prev = GENESIS_RECEIPT_HASH;
        for (i, r) in receipts.iter().enumerate() {
            if r.prev_receipt_hash != expected_prev {
                return (
                    ReceiptStatus::Broken {
                        index: i as u64,
                        reason: ReceiptBreak::ChainMismatch,
                    },
                    expected_prev,
                );
            }
            let body = receipt_body(r);
            let mac = hmac_sha256(self.key.as_bytes(), &body);
            if !ct_eq(&mac, &r.mac) {
                return (
                    ReceiptStatus::Broken {
                        index: i as u64,
                        reason: ReceiptBreak::BadMac,
                    },
                    expected_prev,
                );
            }
            expected_prev = sha256(&body);
        }
        (
            ReceiptStatus::Intact {
                count: receipts.len() as u64,
            },
            expected_prev,
        )
    }

    /// Verifies a slice of receipts against this chain's key: walks the
    /// `prev_receipt_hash` links from genesis and re-checks each MAC. This is
    /// *prefix* verification; it does not detect dropped trailing receipts (see
    /// [`ReceiptChain::verify_complete`]).
    #[must_use]
    pub fn verify(&self, receipts: &[ToolReceipt]) -> ReceiptStatus {
        self.walk(receipts).0
    }

    /// Verifies that `receipts` is the **complete** minted chain: every receipt
    /// valid *and* the final chain hash and count match this chain's head/count.
    /// Detects trailing-receipt deletion that bare [`ReceiptChain::verify`]
    /// cannot (`docs/receipts.md` §6).
    #[must_use]
    pub fn verify_complete(&self, receipts: &[ToolReceipt]) -> ReceiptStatus {
        let (status, final_head) = self.walk(receipts);
        match status {
            ReceiptStatus::Broken { .. } => status,
            ReceiptStatus::Intact { count } => {
                if count != self.count || final_head != self.head {
                    ReceiptStatus::Broken {
                        index: count,
                        reason: ReceiptBreak::EndTruncated,
                    }
                } else {
                    ReceiptStatus::Intact { count }
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key() -> MacKey {
        MacKey::new([7u8; 32])
    }

    fn params(seq: u64, result: &'static [u8]) -> ReceiptParams<'static> {
        ReceiptParams {
            task_id: TaskId(1),
            job_id: JobId(1),
            tool_call_id: ToolCallId(u128::from(seq)),
            tool_name: b"run_command",
            args: b"cargo test",
            result,
            artifacts: &[],
            event_seq: EventSeq(seq),
        }
    }

    fn chain_of(n: u64) -> (ReceiptChain, Vec<ToolReceipt>) {
        let mut chain = ReceiptChain::new(key());
        let mut receipts = Vec::new();
        for i in 1..=n {
            receipts.push(chain.mint(&params(i, b"ok")));
        }
        (chain, receipts)
    }

    #[test]
    fn minted_chain_verifies() {
        let (chain, receipts) = chain_of(3);
        assert_eq!(chain.len(), 3);
        assert_eq!(chain.verify(&receipts), ReceiptStatus::Intact { count: 3 });
        assert_eq!(receipts[0].prev_receipt_hash, GENESIS_RECEIPT_HASH);
        assert!(receipts[1].links_to(&receipts[0]));
        assert!(receipts[2].links_to(&receipts[1]));
    }

    #[test]
    fn result_matches_only_the_real_result() {
        let mut chain = ReceiptChain::new(key());
        let r = chain.mint(&params(1, b"tests passed"));
        assert!(r.result_matches(b"tests passed"));
        assert!(!r.result_matches(b"tests failed"));
    }

    // A receipt forged under the wrong key fails MAC verification.
    #[test]
    fn forged_receipt_under_wrong_key_fails() {
        let (_chain, receipts) = chain_of(2);
        let attacker = ReceiptChain::new(MacKey::new([0xaa; 32]));
        match attacker.verify(&receipts) {
            ReceiptStatus::Broken { index, reason } => {
                assert_eq!(index, 0);
                assert_eq!(reason, ReceiptBreak::BadMac);
            }
            other => panic!("expected bad MAC, got {other:?}"),
        }
    }

    // Tampering with a receipt's result_hash invalidates its MAC.
    #[test]
    fn tampered_result_hash_breaks_mac() {
        let (chain, mut receipts) = chain_of(2);
        receipts[0].result_hash[0] ^= 0xff;
        match chain.verify(&receipts) {
            ReceiptStatus::Broken { index, reason } => {
                assert_eq!(index, 0);
                assert_eq!(reason, ReceiptBreak::BadMac);
            }
            other => panic!("expected bad MAC, got {other:?}"),
        }
    }

    // Reordering receipts breaks the prev-hash chain.
    #[test]
    fn reordered_receipts_break_chain() {
        let (chain, receipts) = chain_of(3);
        let reordered = vec![
            receipts[0].clone(),
            receipts[2].clone(),
            receipts[1].clone(),
        ];
        match chain.verify(&reordered) {
            ReceiptStatus::Broken { index, reason } => {
                assert_eq!(index, 1);
                assert_eq!(reason, ReceiptBreak::ChainMismatch);
            }
            other => panic!("expected chain mismatch, got {other:?}"),
        }
    }

    // Dropping trailing receipts verifies as a prefix but is caught by the
    // anchored verify_complete (against the chain's head/count).
    #[test]
    fn end_truncation_detected_by_verify_complete() {
        let (chain, receipts) = chain_of(3);
        let prefix = vec![receipts[0].clone(), receipts[1].clone()];
        // Bare verify: the 2-receipt prefix is internally consistent.
        assert!(chain.verify(&prefix).is_intact());
        // Anchored verify against the full chain head/count: detected.
        match chain.verify_complete(&prefix) {
            ReceiptStatus::Broken { reason, .. } => assert_eq!(reason, ReceiptBreak::EndTruncated),
            other => panic!("expected end-truncation, got {other:?}"),
        }
        // The full set verifies complete; the head is non-genesis after minting.
        assert!(chain.verify_complete(&receipts).is_intact());
        assert_ne!(chain.head(), GENESIS_RECEIPT_HASH);
    }

    // Deleting a receipt breaks the chain.
    #[test]
    fn deleted_receipt_breaks_chain() {
        let (chain, receipts) = chain_of(3);
        let without_middle = vec![receipts[0].clone(), receipts[2].clone()];
        assert!(!chain.verify(&without_middle).is_intact());
    }

    #[test]
    fn mac_key_debug_is_redacted() {
        assert_eq!(format!("{:?}", key()), "MacKey(***)");
    }
}
