// SPDX-License-Identifier: Apache-2.0
//! Tool receipts (`ROADMAP.md` §7.4; Phase 2). Defends against hallucinated tool
//! results (invariant 10): **no receipt ⇒ no model-visible claim that a tool
//! ran.** Receipts are generated by CrustCore, never the model, and are verified
//! during replay/inspect (`docs/receipts.md`).
#![forbid(unsafe_code)]

use crustcore_types::{ArtifactId, EventSeq, JobId, TaskId, ToolCallId};

/// A receipt binding a model-visible tool result to a real tool call.
///
/// Contains only hashes and ids — **never** secret values (invariant 10).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ToolReceipt {
    /// Task the call ran under.
    pub task_id: TaskId,
    /// Job the call ran under.
    pub job_id: JobId,
    /// The specific tool call.
    pub tool_call_id: ToolCallId,
    /// Hash of the tool name.
    pub tool_name_hash: [u8; 32],
    /// Hash of the (canonicalized) arguments.
    pub args_hash: [u8; 32],
    /// Hash of the result.
    pub result_hash: [u8; 32],
    /// Hashes of any artifacts produced (bounded).
    pub artifact_hashes: Vec<ArtifactId>,
    /// The event sequence this receipt corresponds to.
    pub event_seq: EventSeq,
    /// Hash of the previous receipt (chains receipts).
    pub prev_receipt_hash: [u8; 32],
    /// MAC over the receipt (keyed by CrustCore, not the model).
    pub mac: [u8; 32],
}

impl ToolReceipt {
    /// Verifies this receipt links to `prev` and that its MAC is valid.
    ///
    /// TODO(P2.3): implement MAC verification (keyed BLAKE3/HMAC) and chain
    /// linkage; the scaffold checks only structural linkage.
    #[must_use]
    pub fn links_to(&self, prev: &ToolReceipt) -> bool {
        // Placeholder: a real implementation compares `self.prev_receipt_hash`
        // to a hash of `prev`. Phase 2 wires the actual hashing.
        self.event_seq.0 > prev.event_seq.0
    }
}
